name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    timeout-minutes: 30

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2

      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          test-rust: ${{runner.os == 'Linux'}}
          test-node: true
          node-version: "22" # Node 24 requires C++20 but tree-sitter specifies C++17
          test-python: true
          test-go: true
          go-version: "1.25"
          test-swift: ${{runner.os == 'macOS'}}
        env:
          npm_config_legacy_peer_deps: true

      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files: |-
            examples/svelte/**/*.svelte
            !examples/svelte/packages/svelte/tests/migrate/samples/impossible-migrate-with-errors/input.svelte
            !examples/svelte/packages/svelte/tests/migrate/samples/impossible-migrate-with-errors/output.svelte
            !examples/svelte/packages/svelte/tests/migrate/samples/svelte-self-name-conflict/output.svelte
            !examples/svelte/packages/svelte/tests/preprocess/samples/script-self-closing/input.svelte
            !examples/svelte/packages/svelte/tests/preprocess/samples/style-self-closing/input.svelte
            !examples/svelte/packages/svelte/tests/runtime-legacy/samples/escape-template-literals/main.svelte
            !examples/svelte/packages/svelte/tests/runtime-legacy/samples/unchanged-expression-escape/main.svelte
            # Contains unescaped "&" which breaks HTML parsing
            !examples/svelte/packages/svelte/tests/runtime-runes/samples/each-updates-6/main.svelte
            !examples/svelte/packages/svelte/tests/runtime-runes/samples/each-updates-7/main.svelte
          invalid-files: |-
            examples/svelte/packages/svelte/tests/compiler-errors/**/*
            examples/svelte/packages/svelte/tests/parser-legacy/samples/implicitly-closed-li-block/input.svelte
            examples/svelte/packages/svelte/tests/parser-legacy/samples/loose-invalid-block/input.svelte
            examples/svelte/packages/svelte/tests/parser-legacy/samples/loose-invalid-expression/input.svelte
            examples/svelte/packages/svelte/tests/parser-legacy/samples/loose-unclosed-block/input.svelte
            examples/svelte/packages/svelte/tests/parser-legacy/samples/loose-unclosed-open-tag/input.svelte
            examples/svelte/packages/svelte/tests/parser-legacy/samples/loose-unclosed-tag/input.svelte
            examples/svelte/packages/svelte/tests/parser-legacy/samples/textarea-end-tag/input.svelte
            examples/svelte/packages/svelte/tests/parser-modern/samples/loose-invalid-block/input.svelte
            examples/svelte/packages/svelte/tests/parser-modern/samples/loose-invalid-expression/input.svelte
            examples/svelte/packages/svelte/tests/parser-modern/samples/loose-unclosed-open-tag/input.svelte
            examples/svelte/packages/svelte/tests/parser-modern/samples/loose-unclosed-tag/input.svelte
            examples/svelte/packages/svelte/tests/validator/samples/attribute-expected-equals/input.svelte
            examples/svelte/packages/svelte/tests/validator/samples/attribute-invalid-name/input.svelte
            examples/svelte/packages/svelte/tests/validator/samples/html-block-in-attribute/input.svelte
            examples/svelte/packages/svelte/tests/validator/samples/logic-block-in-attribute/input.svelte
